services:
  hiraeth:
    build:
      context: .
    image: hiraeth:static
    stop_grace_period: 2s
    environment:
      HIRAETH_HOST: 0.0.0.0
      HIRAETH_PORT: 4566
      HIRAETH_WEB_HOST: 0.0.0.0
      HIRAETH_WEB_PORT: 4567
      HIRAETH_DATABASE_URL: sqlite:///data/db.sqlite
    ports:
      - "4566:4566"
      - "4567:4567"

