CREATE TABLE sqs_queues (
  id INTEGER PRIMARY KEY NOT NULL,
  name TEXT NOT NULL,
  region TEXT NOT NULL,
  account_id TEXT NOT NULL,
  queue_type TEXT NOT NULL,
  visibility_timeout_seconds INTEGER NOT NULL,
  delay_seconds INTEGER NOT NULL,
  maximum_message_size INTEGER NOT NULL,
  message_retention_period_seconds INTEGER NOT NULL,
  receive_message_wait_time_seconds INTEGER NOT NULL,
  policy TEXT NOT NULL,
  redrive_policy TEXT NOT NULL,
  content_based_deduplication INTEGER NOT NULL,
  kms_master_key_id TEXT,
  kms_data_key_reuse_period_seconds INTEGER NOT NULL,
  deduplication_scope TEXT NOT NULL,
  fifo_throughput_limit TEXT NOT NULL,
  redrive_allow_policy TEXT NOT NULL,
  sqs_managed_sse_enabled INTEGER NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(name, region, account_id)
);
